# Replace LINK-TO-TARBALL with the package URL you would like to use.
curl -LO https://github.com/tektoncd/cli/releases/download/v0.40.0/tkn_0.40.0_Linux_x86_64.tar.gz
# Replace YOUR-DOWNLOADED-FILE with the file path of your own.
sudo tar xvzf tkn_0.40.0_Linux_x86_64.tar.gz -C /usr/local/bin/ tkn