kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: run-basic-pipeline-from-git
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/hershellayton95/tekton-tests
    - name: revision
      value: main
    - name: pathInRepo
      value: ./resolver/git/pipeline.yaml
  params:
  - name: username
    value: filippo
