apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-dockerfile
spec:
  workspaces:
  - name: source
  steps:
  - name: add-dockerfile
    workingDir: $(workspaces.source.path)
    image: bash
    script: |
      cat <<EOF > Dockerfile
      FROM floryn90/hugo:ext-alpine
      USER root
      RUN apk add git && git config --global --add safe.directory /src
      USER hugo
      EOF