
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: remote-task-reference
spec:
  taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: docker.io/hershellayton95/tekton-hello-bundle:0.0.4
    - name: name
      value: hello-task
    - name: kind
      value: task